name: Compile the extension

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Node 18 📦
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies 🧰
        run: |
          npm ci
          npm install -g @vscode/vsce

      - name: Build and package the extension 🔧
        run: |
          # Equivalent to a dry run of the publish command
          # Runs the prepublish script, which runs the compile script
          vsce ls
